<?php

function fetchBypassCookie($url) {
    $ch = curl_init($url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
    curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
    curl_setopt($ch, CURLOPT_USERAGENT, 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)');
    $html = curl_exec($ch);
    curl_close($ch);

    if (preg_match('/a=toNumbers\("([0-9a-f]+)"\).*?b=toNumbers\("([0-9a-f]+)"\).*?c=toNumbers\("([0-9a-f]+)"\)/i', $html, $matches)) {
        $key = hex2bin($matches[1]);
        $iv = hex2bin($matches[2]);
        $ciphertext = hex2bin($matches[3]);

        // slowAES.decrypt(c, 2, a, b) => AES-256-CBC
        $decrypted = openssl_decrypt($ciphertext, 'aes-256-cbc', $key, OPENSSL_RAW_DATA | OPENSSL_NO_PADDING, $iv);
        
        if ($decrypted !== false) {
            $cookieVal = bin2hex($decrypted);
            echo "Calculated Cookie: __test=$cookieVal\n";
            return "__test=$cookieVal; expires=Thu, 31-Dec-37 23:55:55 GMT; path=/";
        } else {
            echo "Failed to decrypt.\n";
        }
    } else {
        echo "Could not find a, b, c variables.\nHtml:\n$html\n";
    }
    return false;
}

$url = 'https://databasehritikai.techelevatex.us.cc/api.php';
$cookie = fetchBypassCookie($url);
if ($cookie) {
    echo "Successfully generated bypass cookie.\n";
    
    // Test API with the new cookie following redirect
    $ch2 = curl_init($url . "?i=1");
    curl_setopt($ch2, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch2, CURLOPT_SSL_VERIFYPEER, false);
    curl_setopt($ch2, CURLOPT_SSL_VERIFYHOST, false);
    curl_setopt($ch2, CURLOPT_USERAGENT, 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)');
    curl_setopt($ch2, CURLOPT_COOKIE, $cookie);
    $res = curl_exec($ch2);
    curl_close($ch2);
    
    echo "API Response: " . substr($res, 0, 500) . "\n";
}
