<?php
namespace Core\GenerativeAI;

use Core\NLU\EntityExtractor;

class CodeSynthesizer {
    public function generate(string $prompt): string {
        $extractor = new EntityExtractor();
        $entities = $extractor->extract($prompt);
        
        $structures = $entities['programming']['structures'] ?? [];
        $vars = $entities['programming']['variables'] ?? [];
        
        if (empty($structures)) {
            if (preg_match('/(loop|for|while)/i', $prompt)) $structures[] = 'loop';
            if (preg_match('/(class|object)/i', $prompt)) $structures[] = 'class';
            if (preg_match('/(db|database|sql)/i', $prompt)) $structures[] = 'database';
            if (preg_match('/(api|fetch)/i', $prompt)) $structures[] = 'api';
        }

        if (empty($structures)) {
            // Default to a function if no specific structure is requested
            $structures[] = 'function';
        }

        $code = "<?php\n// Generated by Hritik AI Neural Code Synthesizer (Native ML)\n\n";

        if (in_array('class', $structures) || in_array('oop', $structures)) {
            $className = !empty($vars) ? ucfirst($vars[0]) : "Neural" . ucfirst(substr(md5(uniqid()), 0, 5));
            $code .= "class {$className} {\n";
            $code .= "    public function __construct() {\n        // Initialization\n    }\n";
            
            if (in_array('function', $structures) || count($structures) === 1) {
                 $funcName = count($vars) > 1 ? strtolower($vars[1]) : "processData";
                 $code .= "\n    public function {$funcName}() {\n        // Core Logic\n        return true;\n    }\n";
            }
            $code .= "}\n";
        } elseif (in_array('loop', $structures)) {
            $code .= "for (\$i = 0; \$i < 10; \$i++) {\n";
            $code .= "    // Loop Logic\n";
            $code .= "    echo \$i . \"\\n\";\n";
            $code .= "}\n";
        } elseif (in_array('database', $structures) || in_array('sql', $structures)) {
            $code .= "\$db = new PDO('mysql:host=localhost;dbname=test', 'root', '');\n";
            $code .= "\$stmt = \$db->prepare('SELECT * FROM users');\n";
            $code .= "\$stmt->execute();\n";
            $code .= "\$results = \$stmt->fetchAll(PDO::FETCH_ASSOC);\n";
        } elseif (in_array('api', $structures)) {
            $code .= "\$ch = curl_init('https://api.example.com/data');\n";
            $code .= "curl_setopt(\$ch, CURLOPT_RETURNTRANSFER, true);\n";
            $code .= "\$response = curl_exec(\$ch);\n";
            $code .= "curl_close(\$ch);\n";
            $code .= "\$data = json_decode(\$response, true);\n";
        } else {
            $funcName = !empty($vars) ? strtolower($vars[0]) : "executeTask";
            $code .= "function {$funcName}() {\n";
            $code .= "    // Auto-generated logic for: " . addslashes($prompt) . "\n";
            $code .= "    return true;\n";
            $code .= "}\n";
        }

        return "Maine aapki requirement ko samajh kar natively ye PHP code generate kiya hai:\n\n```php\n" . $code . "\n```";
    }
}
