<?php
namespace Core\GenerativeAI;

use Core\NLU\EntityExtractor;

class CodeSynthesizer {
    public function generate(string $prompt): string {
        // Integrate external LLM call for intelligent code generation
        if (file_exists(dirname(__DIR__, 2) . '/env.php')) {
            require_once dirname(__DIR__, 2) . '/env.php';
        }

        $provider = defined('LLM_PROVIDER') ? LLM_PROVIDER : 'local_php';

        if ($provider !== 'local_php') {
            $llmResponse = $this->callExternalLLM("You are an expert programmer. Output only code without any explanations. Generate code for the following request: " . $prompt, $provider);
            if ($llmResponse !== null) {
                return "Maine aapki requirement ko samajh kar natively ye PHP code generate kiya hai:\n\n" . $llmResponse;
            }
        }

        // Fallback to static generation if API is down or local_php
        $extractor = new EntityExtractor();
        $entities = $extractor->extract($prompt);
        
        $structures = $entities['programming']['structures'] ?? [];
        $vars = $entities['programming']['variables'] ?? [];
        
        if (empty($structures)) {
            if (preg_match('/(loop|for|while)/i', $prompt)) $structures[] = 'loop';
            if (preg_match('/(class|object)/i', $prompt)) $structures[] = 'class';
            if (preg_match('/(db|database|sql)/i', $prompt)) $structures[] = 'database';
            if (preg_match('/(api|fetch)/i', $prompt)) $structures[] = 'api';
        }

        if (empty($structures)) {
            $structures[] = 'function';
        }

        $code = "<?php\n// Generated by Hritik AI Neural Code Synthesizer (Fallback Mode)\n\n";

        if (in_array('class', $structures) || in_array('oop', $structures)) {
            $className = !empty($vars) ? ucfirst($vars[0]) : "Neural" . ucfirst(substr(md5(uniqid()), 0, 5));
            $code .= "class {$className} {\n";
            $code .= "    public function __construct() {\n        // Initialization\n    }\n";
            
            if (in_array('function', $structures) || count($structures) === 1) {
                 $funcName = count($vars) > 1 ? strtolower($vars[1]) : "processData";
                 $code .= "\n    public function {$funcName}() {\n        // Core Logic\n        return true;\n    }\n";
            }
            $code .= "}\n";
        } elseif (in_array('loop', $structures)) {
            $code .= "for (\$i = 0; \$i < 10; \$i++) {\n";
            $code .= "    // Loop Logic\n";
            $code .= "    echo \$i . \"\\n\";\n";
            $code .= "}\n";
        } elseif (in_array('database', $structures) || in_array('sql', $structures)) {
            $code .= "\$db = new PDO('mysql:host=localhost;dbname=test', 'root', '');\n";
            $code .= "\$stmt = \$db->prepare('SELECT * FROM users');\n";
            $code .= "\$stmt->execute();\n";
            $code .= "\$results = \$stmt->fetchAll(PDO::FETCH_ASSOC);\n";
        } elseif (in_array('api', $structures)) {
            $code .= "\$ch = curl_init('https://api.example.com/data');\n";
            $code .= "curl_setopt(\$ch, CURLOPT_RETURNTRANSFER, true);\n";
            $code .= "\$response = curl_exec(\$ch);\n";
            $code .= "curl_close(\$ch);\n";
            $code .= "\$data = json_decode(\$response, true);\n";
        } else {
            $funcName = !empty($vars) ? strtolower($vars[0]) : "executeTask";
            $code .= "function {$funcName}() {\n";
            $code .= "    // Auto-generated logic for: " . addslashes($prompt) . "\n";
            $code .= "    return true;\n";
            $code .= "}\n";
        }

        return "Maine aapki requirement ko samajh kar natively ye PHP code generate kiya hai (fallback mode):\n\n```php\n" . $code . "\n```";
    }

    private function callExternalLLM(string $prompt, string $provider): ?string {
        if ($provider === 'gemini') {
            $apiKey = defined('GEMINI_API_KEY') ? GEMINI_API_KEY : '';
            if (empty($apiKey)) return null;

            $url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=" . $apiKey;
            $data = [
                'contents' => [
                    ['parts' => [['text' => $prompt]]]
                ]
            ];

            $ch = curl_init($url);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
            curl_setopt($ch, CURLOPT_POST, true);
            curl_setopt($ch, CURLOPT_HTTPHEADER, ['Content-Type: application/json']);
            curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data));
            $response = curl_exec($ch);
            curl_close($ch);

            if ($response) {
                $json = json_decode($response, true);
                return $json['candidates'][0]['content']['parts'][0]['text'] ?? null;
            }
        } elseif ($provider === 'openai') {
            $apiKey = defined('OPENAI_API_KEY') ? OPENAI_API_KEY : '';
            if (empty($apiKey)) return null;

            $url = "https://api.openai.com/v1/chat/completions";
            $data = [
                'model' => 'gpt-3.5-turbo',
                'messages' => [
                    ['role' => 'system', 'content' => "You are an expert programmer. Only output code."],
                    ['role' => 'user', 'content' => $prompt]
                ]
            ];

            $ch = curl_init($url);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
            curl_setopt($ch, CURLOPT_POST, true);
            curl_setopt($ch, CURLOPT_HTTPHEADER, [
                'Content-Type: application/json',
                'Authorization: Bearer ' . $apiKey
            ]);
            curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data));
            $response = curl_exec($ch);
            curl_close($ch);

            if ($response) {
                $json = json_decode($response, true);
                return $json['choices'][0]['message']['content'] ?? null;
            }
        } elseif ($provider === 'ollama') {
            $url = defined('OLLAMA_ENDPOINT') ? OLLAMA_ENDPOINT : 'http://localhost:11434/api/generate';
            $model = defined('OLLAMA_MODEL') ? OLLAMA_MODEL : 'llama3';

            $data = [
                'model' => $model,
                'prompt' => $prompt,
                'stream' => false
            ];

            $ch = curl_init($url);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
            curl_setopt($ch, CURLOPT_POST, true);
            curl_setopt($ch, CURLOPT_HTTPHEADER, ['Content-Type: application/json']);
            curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data));
            curl_setopt($ch, CURLOPT_TIMEOUT, 3);
            $response = curl_exec($ch);
            curl_close($ch);

            if ($response) {
                $json = json_decode($response, true);
                return $json['response'] ?? null;
            }
        }

        return null;
    }
}
