<?php
namespace Core\Commands;

use Core\Tools\FileSystem\FileEditor;

class CreateProjectCommand implements CommandInterface {
    private FileEditor $fileSystem;

    public function __construct(FileEditor $fileSystem) {
        $this->fileSystem = $this->fileSystem ?? $fileSystem;
    }

    public function canProcess(string $task): bool {
        return str_contains(strtolower($task), 'create project');
    }

    public function process(string $task): string {
        preg_match('/create project ([\w-]+) with files (.*)/i', $task, $matches);
        if ($matches) {
            $projectName = $matches[1];
            $files = explode(',', $matches[2]);
            
            // Basic scaffolding logic
            foreach ($files as $file) {
                $filePath = trim($file);
                $this->fileSystem->writeFile($projectName . '/' . $filePath, "<?php\n// Autogenerated by Hritik AI\n");
            }
            return "[AGENT] Project '$projectName' created successfully with " . count($files) . " files.";
        }
        return "[AGENT] Incomplete 'create project' command. Use: create project <name> with files <a,b,c>";
    }
}
